<a href="https://colab.research.google.com/github/RifaAnwar/Implementasi-arsitektur-Fully-connected-layer/blob/main/Implementasi%20arsitektur%20Fully%20connected%20layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Junior / Associate Data Scientist**

#Implementasi arsitektur Fully connected layer

In [ ]:
import numpy as np
import pandas as pd
import keras
import tensorflow
from sklearn.preprocessing import OneHotEncoder
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D
from sklearn.model_selection import train_test_split
from tensorflow.keras.datasets import mnist
from keras.utils import np_utils

In [ ]:
mnist=mnist.load_data()

In [ ]:
(x_train,y_train),(x_test,y_test)=mnist
x_train,x_val,y_train,y_val=train_test_split(x_train,y_train,test_size=1/12, random_state=42)
x_train=x_train.reshape(x_train.shape[0],28,28,1).astype('float32')
x_test=x_test.reshape(x_test.shape[0],28,28,1).astype('float32')

In [ ]:
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)

In [ ]:
print("data training",x_train.shape)
print("data test",x_test.shape)
print("data validasi",x_val.shape)

data training (55000, 28, 28, 1)
data test (10000, 28, 28, 1)
data validasi (5000, 28, 28)


In [ ]:
encoder = OneHotEncoder()
encode = encoder.fit_transform(x_val.reshape(-1, 1)).toarray()
print(encode)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


##membuat Model

In [ ]:
model=Sequential()
model.add(Conv2D(32,(3,3), input_shape=(28,28,1),activation='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10,activation='softmax'))

##Menjalankan model

In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 13, 13, 32)        0         
                                                                 
 flatten (Flatten)           (None, 5408)              0         
                                                                 
 dense (Dense)               (None, 64)                346176    
                                                                 
 dropout_1 (Dropout)         (None, 64)                0         
                                                        

##Model fitting

In [ ]:
Mf=model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10, batch_size=200, verbose=1)

Epoch 1/10
275/275 [==============================] - 33s 119ms/step - loss: 0.6576 - accuracy: 0.7605 - val_loss: 0.1874 - val_accuracy: 0.9606
Epoch 2/10
275/275 [==============================] - 29s 106ms/step - loss: 0.5279 - accuracy: 0.8130 - val_loss: 0.1336 - val_accuracy: 0.9702
Epoch 3/10
275/275 [==============================] - 29s 105ms/step - loss: 0.4608 - accuracy: 0.8355 - val_loss: 0.1298 - val_accuracy: 0.9716
Epoch 4/10
275/275 [==============================] - 31s 111ms/step - loss: 0.4074 - accuracy: 0.8536 - val_loss: 0.1079 - val_accuracy: 0.9733
Epoch 5/10
275/275 [==============================] - 29s 106ms/step - loss: 0.3508 - accuracy: 0.8783 - val_loss: 0.0907 - val_accuracy: 0.9763
Epoch 6/10
275/275 [==============================] - 29s 106ms/step - loss: 0.3004 - accuracy: 0.8951 - val_loss: 0.0884 - val_accuracy: 0.9764
Epoch 7/10
275/275 [==============================] - 32s 118ms/step - loss: 0.2779 - accuracy: 0.9038 - val_loss: 0.0897 - val_ac

##uji Model

In [ ]:
y_pred=model.predict(x_test)
y_pred=(y_pred>0.5)

313/313 [==============================] - 2s 6ms/step


##confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix
y_pred=model.predict(x_test)
y_pred_one_hot=np.argmax(y_pred,axis=1)
y_test_one_hot=np.argmax(y_test,axis=1)
CM=confusion_matrix(y_test_one_hot,y_pred_one_hot)
print(CM)

313/313 [==============================] - 2s 6ms/step
[[ 970    0    3    0    0    1    1    1    4    0]
 [   0 1126    3    1    1    0    2    0    2    0]
 [   4    3 1016    0    1    0    1    5    2    0]
 [   0    0    2  996    0    6    0    4    2    0]
 [   1    1    1    0  964    0    3    0    3    9]
 [   2    0    0   11    0  871    3    0    5    0]
 [   5    2    0    0    3    4  943    0    1    0]
 [   1    3   12    3    3    0    0 1001    2    3]
 [   7    0    8    1    4    1    1    1  946    5]
 [   9    5    0    6   12    5    0    3    2  967]]


##Evaluasi Model

In [ ]:
from sklearn.metrics import classification_report
report=classification_report(y_test_one_hot,y_pred_one_hot)
print(report)

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.98      0.98      1032
           3       0.98      0.99      0.98      1010
           4       0.98      0.98      0.98       982
           5       0.98      0.98      0.98       892
           6       0.99      0.98      0.99       958
           7       0.99      0.97      0.98      1028
           8       0.98      0.97      0.97       974
           9       0.98      0.96      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000

